# Generated by Django 3.2 on 2022-03-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='授業名')),
                ('semester', models.CharField(blank=True, max_length=5, null=True, verbose_name='前期・後期・その他')),
                ('day', models.CharField(blank=True, max_length=5, null=True, verbose_name='')),
                ('period', models.CharField(blank=True, max_length=5, null=True, verbose_name='時限')),
                ('content', models.TextField(verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '投稿',
                'verbose_name_plural': '投稿一覧',
                'db_table': 'review',
            },
        ),
    ]
