# Generated by Django 3.2 on 2022-03-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='day',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='曜日'),
        ),
    ]
