# Generated by Django 3.2 on 2022-03-09 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, verbose_name='曜日')),
            ],
            options={
                'verbose_name': '曜日',
                'verbose_name_plural': '曜日一覧',
                'db_table': 'day',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10, verbose_name='時限')),
            ],
            options={
                'verbose_name': '時限',
                'verbose_name_plural': '時限一覧',
                'db_table': 'period',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='開講')),
            ],
            options={
                'verbose_name': '開講',
                'verbose_name_plural': '開講一覧',
                'db_table': 'semester',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('no', models.IntegerField(default=0)),
                ('comment', models.TextField(verbose_name='コメント')),
                ('pub_flg', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='review.review')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント一覧',
                'db_table': 'comment',
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='review.day', verbose_name='曜日'),
        ),
        migrations.AlterField(
            model_name='review',
            name='period',
            field=models.ForeignKey(blank=True, max_length=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='review.period', verbose_name='時限'),
        ),
        migrations.AlterField(
            model_name='review',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='review.semester', verbose_name='開講'),
        ),
    ]
