# Generated by Django 3.2 on 2022-03-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20220310_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='ソート'),
        ),
        migrations.AddField(
            model_name='day',
            name='url_code',
            field=models.IntegerField(max_length=10, null=True, unique=True, verbose_name='URLコード'),
        ),
        migrations.AddField(
            model_name='period',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='ソート'),
        ),
        migrations.AddField(
            model_name='period',
            name='url_code',
            field=models.IntegerField(max_length=10, null=True, unique=True, verbose_name='URLコード'),
        ),
    ]
