# Generated by Django 3.2 on 2022-03-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20220313_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='ソート'),
        ),
        migrations.AddField(
            model_name='semester',
            name='url_code',
            field=models.IntegerField(max_length=10, null=True, unique=True, verbose_name='URLコード'),
        ),
    ]
