# Generated by Django 3.2 on 2022-03-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20220313_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='name',
            new_name='semester',
        ),
    ]
