# Generated by Django 3.2 on 2022-03-13 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_rename_name_semester_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='review.day', verbose_name='曜日'),
        ),
        migrations.AlterField(
            model_name='review',
            name='period',
            field=models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.PROTECT, to='review.period', verbose_name='時限'),
        ),
        migrations.AlterField(
            model_name='review',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='review.semester', verbose_name='開講'),
        ),
    ]
