# Generated by Django 3.2 on 2022-03-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20220314_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='url_code',
            field=models.IntegerField(null=True, unique=True, verbose_name='URLコード'),
        ),
        migrations.AlterField(
            model_name='period',
            name='url_code',
            field=models.IntegerField(null=True, unique=True, verbose_name='URLコード'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='url_code',
            field=models.IntegerField(null=True, unique=True, verbose_name='URLコード'),
        ),
    ]
