# Generated by Django 4.1.1 on 2022-09-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0008_auto_20220322_2129"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="pub_flg", new_name="pub_fig",
        ),
    ]
