# Generated by Django 4.1.1 on 2022-09-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0009_rename_pub_flg_comment_pub_fig"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="created", new_name="created_at",
        ),
    ]
