# Generated by Django 4.1.1 on 2022-09-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0010_rename_created_comment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
