# Generated by Django 4.1.1 on 2022-09-17 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0011_review_is_public"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "クチコミ", "verbose_name_plural": "クチコミ一覧"},
        ),
    ]
