# Generated by Django 4.2 on 2023-07-26 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, verbose_name='IPアドレス')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.review')),
            ],
        ),
    ]
