# Generated by Django 4.2 on 2023-07-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='本文')),
                ('anser', models.TextField(blank=True, null=True, verbose_name='回答')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '質問',
                'verbose_name_plural': '質問一覧',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='タグ名')),
                ('url_code', models.IntegerField(null=True, unique=True, verbose_name='URLコード')),
                ('sort', models.IntegerField(default=0, verbose_name='ソート')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ一覧',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, verbose_name='IPアドレス')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QandA.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QandA.tag', verbose_name='タグ'),
        ),
        migrations.CreateModel(
            name='QComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('no', models.IntegerField(default=0)),
                ('comment', models.TextField(verbose_name='コメント')),
                ('pub_fig', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QandA.question')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント一覧',
                'db_table': 'qcomment',
            },
        ),
    ]
