# Generated by Django 4.2 on 2023-07-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcomment',
            old_name='review',
            new_name='question',
        ),
    ]
