# Generated by Django 4.2 on 2023-09-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0002_rename_review_qcomment_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20, verbose_name='学科名')),
                ('url_code', models.IntegerField(null=True, unique=True, verbose_name='URLコード')),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '学科一覧',
                'db_table': 'department',
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'カテゴリ', 'verbose_name_plural': 'カテゴリ一覧'},
        ),
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QandA.tag', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=20, verbose_name='カテゴリ名'),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=20, verbose_name='学部名')),
                ('url_code', models.IntegerField(null=True, unique=True, verbose_name='URLコード')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QandA.department', verbose_name='学科')),
            ],
            options={
                'verbose_name': '学部',
                'verbose_name_plural': '学部一覧',
                'db_table': 'faculty',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='faculty_and_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='QandA.faculty', verbose_name='学部'),
        ),
    ]
