# Generated by Django 4.2 on 2023-09-22 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0003_department_alter_tag_options_alter_question_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='faculty_and_department',
            new_name='faculty',
        ),
        migrations.AddField(
            model_name='question',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='QandA.department', verbose_name='学科'),
        ),
    ]
