# Generated by Django 4.2 on 2023-10-26 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("QandA", "0005_remove_question_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="department",
        ),
        migrations.AddField(
            model_name="department",
            name="faculty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="QandA.faculty",
                verbose_name="学部",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="QandA.department",
                verbose_name="学科",
            ),
        ),
    ]
